### ISSUE TITLE
Eclipse download mirror does not have the requested file

### ISSUE THREAD

**Issue by grubeninspekteur** [devonfw/ide-urls#17]
Failed to download https://ftp.snt.utwente.nl/pub/software/eclipse/technology/epp/downloads/release/2024-03/R/eclipse-java-2024-03-R-win32-x86_64.zip with exit code 22

Instead of pinning the mirror, I would recommend using automatic mirror selection. See: https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2024-09/R/eclipse-inst-jre-win64.exe

=> Direct link to file

https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2024-09/R/eclipse-inst-jre-win64.exe&r=1

**Comment by hohwille** [comment]
Sorry for this problem. And thanks for reporting...
Mirrors should never remove releases afterwards. See: https://github.com/devonfw/IDEasy/blob/main/documentation/tool-vendor-plea.adoc#stable-and-consistent-download-urls
Unfortunately nobody listens to our plea...

However, we also need to change our UrlUpdater and will try to switch to https://ftp.snt.utwente.nl/pub/software/eclipse/technology/epp/downloads/release/ 

Need to be fixed here:
https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/tool/eclipse/EclipseUrlUpdater.java

I am on vacation and will be back next week. I try to delegate to some other developer.
If someone is blocked, try to create a PR for the eclipse version you need in your project that manually fixes the URL and we can merge to unblock your project. Otherwise some patience is required.

**Comment by hohwille** [comment]
> Only 2024-06 and 2024-09 are present.

Versions 2020-* and 2021-* also work.

**Comment by hohwille** [comment]
@grubeninspekteur could you please give feedback if the problem is fixed now.
At least to the diff I observed produced by the nightly job to update and sync `ide-urls`, it looks as if my fixes seemed to have worked and did their job.
